---
- h_bezel: 0 # in pixels
- v_bezel: 0 # in pixels
- h_index: 0 # zero base, from bottom left
- v_index: 0 # zero base, from bottom left
- h_screens: 2
- v_screens: 2
- width: 1280 # in pixels
- height: 720 # in pixels
- image_location: "../../res/textures/Image_created_with_a_mobile_phone.png"
